%YAML:1.0
---
model_type: MEI
camera_name: camera
image_width: 848
image_height: 800
mirror_parameters:
   xi: 1.8955743202683348
distortion_parameters:
   k1: 0.07721542170007131
   k2: -0.38530251556409134
   p1: 0.0005537966232842353
   p2: -0.002372063412682453
projection_parameters:
   gamma1: 824.8983480963985
   gamma2: 825.4248834627437
   u0: 413.75128115425485
   v0: 395.9999363245009
