%YAML:1.0
---

camera_topic: ["/D430/camera/infra1/image_rect_raw", "/D430/camera/infra2/image_rect_raw"]  # camera topic names
camera_info:  ["cam0_pinhole.yaml",   "cam1_pinhole.yaml"  ]  # camera info file names
camera_mask:  []

# frontend configuration
tracking_type: "general_stereo"       # tracking type: ["virtual_stereo", "general_stereo", "EIS_fisheye"]
max_feature_per_frame: 150            # max feature number in feature tracking
min_feature_distance: 30              # min distance between two features
inv_flow_dis_thresh: 0.5              # inverse flow distance threshold
quality_level: 0.01                   # quality level for Shi-Tomasi corner detection
track_show_status: [1, 1]          # tracking results visualization [enable/disable, draw features, draw ids]
always_keyframe: 1                 # always keyframe: [0, 1]

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.00210612, -0.01045005,  0.99994318,  0.05222201,
          -0.99997532, -0.00672459,  0.00203591,  0.0146902 ,
           0.00670294, -0.99992279, -0.01046396, -0.03623093,
           0.        ,  0.        ,  0.        ,  1.        ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.00159178, -0.01139836,  0.99993377,  0.05242354,
          -0.99997648, -0.00668825,  0.00151561, -0.03531049,
           0.00667053, -0.99991267, -0.01140874, -0.03599585,
           0.        ,  0.        ,  0.        ,  1.        ]
